[[CURRENCIES]]
code = "VRWORLD"
issuer = "GCHMI24KOT53YQFUWTOJBUDSOHLFPTYBKHH2FU2V5XEH5NBPXXKY66SD"
name = "VR WORLD PROJET"
desc = "REPUTA is a digital reputation scoring token on Pi Testnet."
image = "https://vrworld1.github.io/vrworld/smart.png"
website = "https://vrworld1.github.io/vrworld/"
