[[CURRENCIES]]
code = "VRWORLD"
issuer = "GCHMI24KOT53YQFUWTOJBUDSOHLFPTYBKHH2FU2V5XEH5NBPXXKY66SD"
name = "VR WORLD PROJET"
desc = "VRWORLD is a digital VRWORLDtoken on Pi Testnet."
image = "https://vrworld1.github.io/VRLOGO.png"
website = "https://vrworld1.github.io"
