[[CURRENCIES]]
code = "VRWORLD"
issuer = "GCHMI24KOT53YQFUWTOJBUDSOHLFPTYBKHH2FU2V5XEH5NBPXXKY66SD"
name = "VR WORLD PROJET"
desc = "VRWORLD An immersive digital gateway integrating Virtual Reality with Pi Network to offer decentralized, interactive experiences that transcend the boundaries of imagination."
image = "https://vrworld1.github.io/VRLOGO.png"
website = "https://vrworld1.github.io"
